// <auto-generated />
using System;
using Kessler.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Kessler.Infrastructure.Migrations
{
    [DbContext(typeof(KesslerDbContext))]
    partial class KesslerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("RM558652")
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kessler.Domain.Entities.MissionScenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int>("DataConfidence")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double?>("EstimatedDeltaVMps")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("EstimatedDurationDays")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int>("OrbitalObjectId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("PlannedStartUtc")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("OrbitalObjectId");

                    b.ToTable("MISSION_SCENARIOS", "RM558652");
                });

            modelBuilder.Entity("Kessler.Domain.Entities.OrbitalObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AltitudeKm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("DataConfidence")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double?>("EstimatedMassKg")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("EstimatedSizeM")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("InclinationDeg")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int?>("LaunchYear")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("NoradId")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20)");

                    b.Property<int>("OrbitRegion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("ORBITAL_OBJECTS", "RM558652");
                });

            modelBuilder.Entity("Kessler.Domain.Entities.ReuseMaterialEstimate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DataConfidence")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("EstimatedSharePct")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int>("Material")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int>("OrbitalObjectId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PreferredPath")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("RecoveryPotential")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Summary")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("OrbitalObjectId");

                    b.ToTable("REUSE_MATERIAL_ESTIMATES", "RM558652");
                });

            modelBuilder.Entity("Kessler.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USERS", "RM558652");
                });

            modelBuilder.Entity("Kessler.Domain.Entities.MissionScenario", b =>
                {
                    b.HasOne("Kessler.Domain.Entities.OrbitalObject", "OrbitalObject")
                        .WithMany("Missions")
                        .HasForeignKey("OrbitalObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrbitalObject");
                });

            modelBuilder.Entity("Kessler.Domain.Entities.ReuseMaterialEstimate", b =>
                {
                    b.HasOne("Kessler.Domain.Entities.OrbitalObject", "OrbitalObject")
                        .WithMany("MaterialEstimates")
                        .HasForeignKey("OrbitalObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrbitalObject");
                });

            modelBuilder.Entity("Kessler.Domain.Entities.OrbitalObject", b =>
                {
                    b.Navigation("MaterialEstimates");

                    b.Navigation("Missions");
                });
#pragma warning restore 612, 618
        }
    }
}
